name: release-blocklet

on:
  push:
    branches:
      - master-disabled
      - main-disabled
jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache 'yarn'

      - name: Initialize
        run: yarn

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-upload: false
          bundle-command: yarn bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_DEV }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_DEV }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
