name: release-blocklet

on:
  push:
    branches:
      - master
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Initialize
        run: make github-init

      - name: Deploy
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          BLOCKLET_REGISTRY: ${{ secrets.STAGING_REGISTRY }}
          ABTNODE_DEV_SK: ${{ secrets.ABTNODE_DEV_STAGING_SK }}
        run: bash ./tools/publish.sh

      - name: Release to Github
        uses: blocklet/action-release-to-github@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
